import type { DetailedProject } from "../../features/projects/types/project-detail.interface";
import { FaReact, FaNodeJs, FaGithub, FaLinkedin, FaJava } from "react-icons/fa";
import { SiAstro, SiTailwindcss, SiFramer, SiVercel, SiTypescript, SiNextdotjs, SiSupabase, SiPostgresql, SiDocker, SiKubernetes, SiAmazon, SiVuedotjs, SiVite, SiSpringboot, SiJavascript, SiNestjs, SiDotnet } from "react-icons/si";

export const PROJECTS_DETAIL_DATA: DetailedProject[] = [
  {
    id: "car_rental",
    title: "Car Rental Management System",
    shortDescription: "A full-stack vehicle rental management system featuring role-based authentication, fleet management, and booking workflows. Built with Vue 3 and Spring Boot, it offers a complete solution for managing vehicle rental operations.",
    context: "Developed as a complete solution to manage vehicle rental operations, this project showcases full-stack capabilities by integrating a Vue.js frontend with a Spring Boot backend API, offering practical features for customers and administrators.",
    objective: "To build a functional and scalable platform that enables users to browse vehicles, make reservations, and manage car rental workflows through an intuitive web interface and reliable backend infrastructure.",
    highlights: [
      "Role-based authentication for customers, agents, and admins.",
      "Fleet management, booking workflows, and payment handling.",
      "Modern frontend architecture using Vue 3 and Vite.",
      "REST API with Spring Boot, PostgreSQL, and Dockerized development setup.",
      "Automated testing using Cypress and Vitest.",
    ],
    technicalStack: {
      frontend: [
        { name: "Vue 3", description: "Progressive JavaScript framework for building reactive user interfaces.", icon: SiVuedotjs },
        { name: "Vite", description: "Frontend build tool that provides fast development and optimized builds.", icon: SiVite },
        { name: "JavaScript", description: "Used for client-side logic and interactivity within the application.", icon: SiJavascript },
        { name: "Tailwind CSS", description: "Utility-first CSS framework for building custom designs efficiently.", icon: SiTailwindcss },
      ],
      backend: [
        { name: "Java", description: "Primary programming language for backend services and application logic.", icon: FaJava },
        { name: "Spring Boot", description: "Framework for building scalable and production-ready REST APIs.", icon: SiSpringboot },
        { name: "PostgreSQL", description: "Relational database for managing vehicle, user, and transaction data.", icon: SiPostgresql },
      ],
      devOps: [
        { name: "Docker", description: "Containerization tool used to manage and deploy the development environment.", icon: SiDocker },
      ],
    },
    visualContent: {
      mainImage: "/images/car_rental/01.png",
      screenshots: [
        "/images/car_rental/02.png",
        "/images/car_rental/03.png",
        "/images/car_rental/04.png",
        "/images/car_rental/05.png",
        "/images/car_rental/06.png",
        "/images/car_rental/07.png",
        "/images/car_rental/08.png",
        "/images/car_rental/09.png",
        "/images/car_rental/10.png",
        "/images/car_rental/11.png",
        "/images/car_rental/12.png",
        "/images/car_rental/13.png",
        "/images/car_rental/14.png",
        "/images/car_rental/15.png",
        "/images/car_rental/16.png",
        "/images/car_rental/17.png",
        "/images/car_rental/18.png",
      ],
    },

    collaborators: [],
  },
  {
    id: "ecua_ticket",
    title: "Ecua Ticket App",
    shortDescription: "Una aplicación web moderna para la gestión de tickets desarrollada con Next.js 15, TypeScript y HeroUI.",
    context: "Ecua Ticket App es una aplicación de buses web moderna para la gestión de tickets que utiliza una arquitectura limpia y escalable. La aplicación está construida con Next.js 15, TypeScript y HeroUI, proporcionando una experiencia de usuario moderna y responsive.",
    objective: "Gestionar eficientemente la venta y administración de tickets de autobús mediante una plataforma web robusta, escalable y fácil de usar.",
    highlights: [
      "Arquitectura limpia (Clean Architecture) y escalable.",
      "Interfaz de usuario moderna y responsive con HeroUI y Tailwind CSS.",
      "Desarrollo optimizado con Next.js 15 y React 19.",
      "Sistema de autenticación y gestión de usuarios.",
      "Componentes dinámicos y animaciones con Framer Motion.",
    ],
    technicalStack: {
      frontend: [
        { name: "Next.js 15", description: "Framework de React con App Router.", icon: SiNextdotjs },
        { name: "React 19", description: "Biblioteca de interfaz de usuario.", icon: FaReact },
        { name: "TypeScript", description: "Tipado estático para JavaScript.", icon: SiTypescript },
        { name: "Tailwind CSS", description: "Framework CSS utility-first.", icon: SiTailwindcss },
        { name: "Framer Motion", description: "Biblioteca de animaciones.", icon: SiFramer },
      ],
    },
    visualContent: {
      mainImage: "/images/ecua_ticket/b1.png",
      screenshots: [
        "/images/ecua_ticket/b10.png",
        "/images/ecua_ticket/b2.png",
        "/images/ecua_ticket/b3.png",
        "/images/ecua_ticket/b4.png",
        "/images/ecua_ticket/b5.png",
        "/images/ecua_ticket/b6.png",
        "/images/ecua_ticket/b7.png",
        "/images/ecua_ticket/b8.png",
        "/images/ecua_ticket/b9.png",
      ],
    },
    links: {
      github: "https://github.com/vKail/ecua-ticket-app",
    },
    collaborators: [
      { name: "Emilia Galarza", role: "Collaborator", github: "https://github.com/Emi1213" },
      { name: "Adrian Jurado", role: "Collaborator", github: "https://github.com/vKail" },
      { name: "Sebastián Camino", role: "Collaborator", github: "https://github.com/scaminom" },
      { name: "Joshua Herrera", role: "Collaborator", github: "https://github.com/Gokochas10" },
    ],
  },
  {
    id: "savings_goals",
    title: "Savings Goals App",
    shortDescription: "A personal financial management platform designed to help users track and achieve their savings goals. Featuring an AI-powered chat for personalized financial advice and habit recommendations.",
    context: "Aplicación web integral para la gestión de metas de ahorro, dividida en un frontend moderno con Next.js y una API robusta en NestJS. Diseñada para ayudar a los usuarios a optimizar sus hábitos financieros mediante IA.",
    objective: "Proporcionar una herramienta completa para que los usuarios establezcan, sigan y alcancen sus metas de ahorro con asistencia personalizada.",
    highlights: [
      "Autenticación JWT segura e integrada.",
      "Dashboard interactivo para visualizar el progreso de ahorros.",
      "Asistente financiero personal impulsado por IA (OpenRouter).",
      "Notificaciones automáticas vía email y en la aplicación.",
      "Gestión completa (CRUD) de metas, contribuciones y retiros.",
    ],
    technicalStack: {
      frontend: [
        { name: "Next.js 14", description: "Framework de React con App Router.", icon: SiNextdotjs },
        { name: "TypeScript", description: "Tipado estático para robustez.", icon: SiTypescript },
        { name: "Hero UI", description: "Basada en Tailwind CSS para diseño moderno.", icon: SiTailwindcss },
        { name: "Zustand", description: "Gestión de estado ligera y flexible.", icon: SiVercel },
        { name: "Chart.js", description: "Visualización de datos financieros.", icon: SiJavascript },
      ],
      backend: [
        { name: "NestJS", description: "Framework escalable para el servidor.", icon: SiNestjs },
        { name: "PostgreSQL", description: "Base de datos relacional con Prisma ORM.", icon: SiPostgresql },
        { name: "Passport-JWT", description: "Estrategia de autenticación segura.", icon: SiJavascript },
        { name: "OpenRouter AI", description: "Inteligencia artificial para recomendaciones.", icon: SiAmazon },
      ],
      devOps: [
        { name: "Docker", description: "Contenedorización de servicios.", icon: SiDocker },
      ],
    },
    visualContent: {
      mainImage: "/images/savings_goals/dashboard1.jpg",
      screenshots: [
        "/images/savings_goals/Login.jpg",
        "/images/savings_goals/Retiros.jpg",
        "/images/savings_goals/chatbot_general_0.jpg",
        "/images/savings_goals/chatbot_general_1.jpg",
        "/images/savings_goals/chatbot_general_2.jpg",
        "/images/savings_goals/chatbot_general_3.jpg",
        "/images/savings_goals/chatbot_general_4.jpg",
        "/images/savings_goals/chatbot_meta_especifica.jpg",
        "/images/savings_goals/chatbot_meta_especifica_pregunta.jpg",
        "/images/savings_goals/contribuciones.jpg",
        "/images/savings_goals/dasboard_scroll.jpg",
        "/images/savings_goals/dashboard2.jpg",
        "/images/savings_goals/dashboard3.jpg",
        "/images/savings_goals/flujo_general.jpg",
        "/images/savings_goals/metas_ahorro.jpg",
        "/images/savings_goals/metas_ahorro_detail.jpg",
        "/images/savings_goals/metas_ahorro_progreso.jpg",
        "/images/savings_goals/recordatorio_email.jpg",
        "/images/savings_goals/register.jpg",
      ],
    },
    links: {
      github: "https://github.com/Chu2409/saving-goals-api",
    },
    collaborators: [
      { name: "Daniel Zhu", role: "Collaborator", github: "https://github.com/Chu2409" },
      { name: "Joshua Herrera", role: "Collaborator", github: "https://github.com/Gokochas10" },
      { name: "Emilia Galarza", role: "Collaborator", github: "https://github.com/Emi1213" },
      { name: "Oscar Joel Ramírez", role: "Collaborator", github: "https://github.com/OscarJRM" },
    ],
  },
  {
    id: "website",
    title: "CodeCrafters Corporate Website",
    shortDescription: "Sitio web corporativo para un equipo de desarrollo, incluyendo blog y presentación de miembros.",
    context: "Simulación de un sitio web de negocios para el equipo de desarrollo CodeCrafters, diseñado para establecer presencia en línea, publicar artículos técnicos y promocionar a los participantes del equipo.",
    objective: "Desarrollar una plataforma web profesional y moderna que sirva como carta de presentación para el equipo y sus servicios, utilizando tecnologías modernas.",
    highlights: [
      "Diseño corporativo moderno y profesional.",
      "Sección de blog para contenido técnico y noticias.",
      "Showcase de miembros del equipo y sus perfiles.",
      "Optimizado para alto rendimiento y SEO.",
    ],
    technicalStack: {
      frontend: [
        { name: "Next.js", description: "Framework principal para la estructura y SSR.", icon: SiNextdotjs },
        { name: "React", description: "Biblioteca de UI para componentes interactivos.", icon: FaReact },
        { name: "TypeScript", description: "Tipado estático para un desarrollo robusto.", icon: SiTypescript },
        { name: "Tailwind CSS", description: "Estilizado rápido y responsivo.", icon: SiTailwindcss },
      ],
    },
    visualContent: {
      mainImage: "/images/website/w1.png",
      screenshots: [
        "/images/website/w3.png",
        "/images/website/w4.png",
        "/images/website/w5.png",
        "/images/website/w7.png",
      ],
    },
    links: {
      github: "https://github.com/vKail/codecrafters-corporate-website",
    },
    collaborators: [
      { name: "JMSebas", role: "Collaborator", github: "https://github.com/JMSebas" },
      { name: "Emilia Galarza", role: "Collaborator", github: "https://github.com/Emi1213" },
      { name: "Adrian Jurado", role: "Collaborator", github: "https://github.com/vKail" },
      { name: "Daniel Zhu", role: "Collaborator", github: "https://github.com/Chu2409" },
    ],
  },
];
